# Generated by Django 4.1.4 on 2023-10-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ToDo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[("1", "High"), ("2", "Medium"), ("3", "Low")], max_length=2
            ),
        ),
    ]
